version: "3.8"

services:
  frontend:
    depends_on: 
      - backend
    build: ./www
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api/
    networks:
      - test

  backend: 
    depends_on: 
      - db
    build: ./api
    environment: 
      DATABASE_URL: mongodb://db/todo
    command: ./docker-entrypoint.sh
    networks:
      - test

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - todo:/data/db
    networks:
      - test

  nginx:
    depends_on:
      - frontend
      - backend
    restart: always
    build: ./nginx
    ports:
      - 8080:80
    networks:
      - test

volumes:
  todo:

networks:
  test: