version: "3.8"

services:
  frontend:
    depends_on: 
      - backend
    build: ./www
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/

  backend: 
    depends_on: 
      - db
    build: ./api
    ports: 
      - 8000:8000
    environment: 
      DATABASE_URL: mongodb://db/todo
    command: ./docker-entrypoint.sh

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - todo:/data/db

  nginx:
    depends_on:
      - frontend
      - backend
    restart: always
    build: ./nginx
    ports:
      - 8080:80

volumes:
  todo:
